### ISSUE TITLE
Install/setup of the builder issue

### ISSUE THREAD

**Issue by NormanPCN** [Pathoschild/SMAPI-ModTranslationClassBuilder#2]
Not sure where to post this query, but here is where I am putting it.

I thought I would check out this tool. I am getting an error from VS 2019 after installing the NuGet package for translation 2.0. I installed the Microsoft.CodeAnalysis 4.0.1 since the error mentioned CodeAnalysis 4.0 was referenced and that was not in the list of NuGet packages installed.

Here is the error. Warning actually since it appears to be an anaylzer "error". But the I18n class is never generated and thus an I18n.Init becomes an error. 

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	CS8032	An instance of analyzer Pathoschild.Stardew.ModTranslationClassBuilder.TranslationClassBuilder cannot be created from C:\Users\Norman\.nuget\packages\pathoschild.stardew.modtranslationclassbuilder\2.0.0\analyzers\dotnet\cs\Pathoschild.Stardew.ModTranslationClassBuilder.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	CombatControlsRedux		1	Active	Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
-----
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

-----

Here is an excerpt from my source.
        /// <summary>The mod entry point, called after the mod is first loaded.</summary>
        /// <param name="helper">Provides simplified APIs for writing mods.</param>
        public override void Entry(IModHelper helper)
        {
            Instance = this;
            MyHelper = helper;

            I18n.Init(helper.Translation);

---

My i18n default.json file is in a folder i18n.

How I accessed the helper in my code.

Within the main ModEntry class there is this declaration.
        private static ITranslationHelper i18n => Instance.MyHelper.Translation;

Then reading the i18n data is done like
       i18n.Get("mouseFix.Label")

---

Here is my project file
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>CombatControlsRedux</AssemblyName>
    <RootNamespace>CombatControlsRedux</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;MyTest</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CCR bats.mp4" />
    <None Remove="CCR demo.mp4" />
    <None Remove="CCR feature show.mp4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.0.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.0.0" />
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.0.0" />
  </ItemGroup>

</Project>

**Comment by Pathoschild** [comment]
Hi! The latest 2.0.0 update uses newer features, so you might need to install Visual Studio 2022 to use it.

**Comment by NormanPCN** [comment]
Installed VS 2022 and the I18n class now seems to be there. No comp errors and I can view the auto generated class.

Now I can give a go at fixing Better Shop Menu (UI scaling) and maybe add the filter suggestion I previously made.
